export const RootErrorPageTemplate = `// Generated by Bugpilot Wizard
"use client";

import { BasicErrorPage } from "@bugpilot/react-error-pages";
export default BasicErrorPage;
`;

export const getGlobalErrorPageTemplate = (
  workspaceId: string,
) => `// Generated by Bugpilot Wizard
"use client";

import { Bugpilot } from "@bugpilot/plugin-nextjs";
import { BasicErrorPage } from "@bugpilot/react-error-pages";

export default function GlobalErrorPage({
  children,
  ...props
}: React.PropsWithChildren<{
  error: Error & { digest?: string };
  reset: () => void;
}>) {
  // Global Error also catch root layout errors
  // so we need to render the html and body tags here
  return (
    <html lang="en">
      <head>
        <meta charSet="utf-8" />
        <meta name="viewport" content="initial-scale=1.0, width=device-width" />
        <title>Application Error</title>
      </head>
      <body
        style={{
          margin: 0,
          padding: 0,
          height: "100vh",
          width: "100vw",
          fontFamily: "sans-serif",
        }}
      >
        <BasicErrorPage {...props}>{children}</BasicErrorPage>
        <Bugpilot workspaceId="${workspaceId}" />
      </body>
    </html>
  );
}
`;

export const InstallBugpilotCommand = {
  npm: "npm install --save @bugpilot/plugin-nextjs@latest @bugpilot/react-error-pages@latest",
  yarn: "yarn add @bugpilot/plugin-nextjs@latest @bugpilot/react-error-pages@latest",
  pnpm: "pnpm add @bugpilot/plugin-nextjs@latest @bugpilot/react-error-pages@latest",
};
